### ISSUE TITLE
Request Analisis Desain

### ISSUE THREAD

**Issue by IanNarsa** [masjid-it/majikom#1]
Analisis Desainnya minta ya

**Comment by hadihammurabi** [comment]
> Analisis Desainnya minta ya

Belum ada eee, Pak Sep. Ini baru inisiasi, belum buat Analisis dan Desain

**Comment by IanNarsa** [comment]
kita tunggu bala bantuan dulu hehehe

**Comment by hadihammurabi** [comment]
> kita tunggu bala bantuan dulu hehehe

betul sangat ahahaha...

**Comment by hadihammurabi** [comment]
Sudah fix di 7eac0131979c61fd679a00fd40fc41d077347297
